name: Deploy the API

on:
  workflow_call

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Step node
        uses: actions/setup-node@v3
        with:
          node_version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Resart
        run: pm2 restart pm2.config.js