name: Docker SSH Update

on:
  workflow_run:
    workflows: ["First CI"]
    types:
      - completed
    
jobs:
  update:
    if: ${{ github.event.workflow_run.conclusion == "succes" }}
    name: Update Docker Container
    runs-on: ubuntu-latest

    steps:
      - name: Execute ssh update
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}

          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          script: bash update.sh
